
package es.ccn.cursodejavaavanzado.proyectowebservice.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2023-10-26T09:01:55.471+02:00
 * Generated source version: 4.0.3
 *
 */
public final class ClienteService_ClienteServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.proyectowebservice.cursodejavaavanzado.ccn.es/", "ClienteServiceImplService");

    private ClienteService_ClienteServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ClienteServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ClienteServiceImplService ss = new ClienteServiceImplService(wsdlURL, SERVICE_NAME);
        ClienteService port = ss.getClienteServiceImplPort();

        {
        System.out.println("Invoking actualizarCliente...");
        es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente _actualizarCliente_arg0 = new es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente();
        _actualizarCliente_arg0.setApellidos("Apellidos728130866");
        _actualizarCliente_arg0.setId(930395457);
        _actualizarCliente_arg0.setNombre("Nombre1228287857");
        _actualizarCliente_arg0.setNumPedidos(719926949);
        _actualizarCliente_arg0.setStrFechaNacimiento("StrFechaNacimiento336940462");
        port.actualizarCliente(_actualizarCliente_arg0);


        }
        {
        System.out.println("Invoking insertarCliente...");
        es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente _insertarCliente_arg0 = new es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente();
        _insertarCliente_arg0.setApellidos("Apellidos514089018");
        _insertarCliente_arg0.setId(737115010);
        _insertarCliente_arg0.setNombre("Nombre947055722");
        _insertarCliente_arg0.setNumPedidos(-1445552918);
        _insertarCliente_arg0.setStrFechaNacimiento("StrFechaNacimiento539272955");
        port.insertarCliente(_insertarCliente_arg0);


        }
        {
        System.out.println("Invoking obtenerClienteById...");
        int _obtenerClienteById_arg0 = 1176536899;
        es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente _obtenerClienteById__return = port.obtenerClienteById(_obtenerClienteById_arg0);
        System.out.println("obtenerClienteById.result=" + _obtenerClienteById__return);


        }
        {
        System.out.println("Invoking obtenerClientes...");
        java.util.List<es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente> _obtenerClientes__return = port.obtenerClientes();
        System.out.println("obtenerClientes.result=" + _obtenerClientes__return);


        }
        {
        System.out.println("Invoking borrarCliente...");
        int _borrarCliente_arg0 = -1719365133;
        port.borrarCliente(_borrarCliente_arg0);


        }

        System.exit(0);
    }

}
