
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package es.ccn.cursodejavaavanzado.proyectowebservice.service;

import java.util.logging.Logger;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2023-10-26T09:01:55.534+02:00
 * Generated source version: 4.0.3
 *
 */

@jakarta.jws.WebService(
                      serviceName = "ClienteServiceImplService",
                      portName = "ClienteServiceImplPort",
                      targetNamespace = "http://service.proyectowebservice.cursodejavaavanzado.ccn.es/",
                      wsdlLocation = "http://localhost:1234/WS/ClienteService?WSDL",
                      endpointInterface = "es.ccn.cursodejavaavanzado.proyectowebservice.service.ClienteService")

public class ClienteServiceImplPortImpl implements ClienteService {

    private static final Logger LOG = Logger.getLogger(ClienteServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see es.ccn.cursodejavaavanzado.proyectowebservice.service.ClienteService#actualizarCliente(es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente arg0)*
     */
    public void actualizarCliente(es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente arg0) {
        LOG.info("Executing operation actualizarCliente");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see es.ccn.cursodejavaavanzado.proyectowebservice.service.ClienteService#insertarCliente(es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente arg0)*
     */
    public void insertarCliente(es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente arg0) {
        LOG.info("Executing operation insertarCliente");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see es.ccn.cursodejavaavanzado.proyectowebservice.service.ClienteService#obtenerClienteById(int arg0)*
     */
    public es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente obtenerClienteById(int arg0) {
        LOG.info("Executing operation obtenerClienteById");
        System.out.println(arg0);
        try {
            es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente _return = new es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente();
            _return.setApellidos("Apellidos1867793595");
            _return.setId(-465771010);
            _return.setNombre("Nombre1113148780");
            _return.setNumPedidos(1441484388);
            _return.setStrFechaNacimiento("StrFechaNacimiento-894645899");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see es.ccn.cursodejavaavanzado.proyectowebservice.service.ClienteService#obtenerClientes()*
     */
    public java.util.List<es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente> obtenerClientes() {
        LOG.info("Executing operation obtenerClientes");
        try {
            java.util.List<es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente> _return = new java.util.ArrayList<es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente>();
            es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente _returnVal1 = new es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente();
            _returnVal1.setApellidos("Apellidos758191062");
            _returnVal1.setId(-1060445745);
            _returnVal1.setNombre("Nombre-280195441");
            _returnVal1.setNumPedidos(182780337);
            _returnVal1.setStrFechaNacimiento("StrFechaNacimiento464158630");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see es.ccn.cursodejavaavanzado.proyectowebservice.service.ClienteService#borrarCliente(int arg0)*
     */
    public void borrarCliente(int arg0) {
        LOG.info("Executing operation borrarCliente");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
