
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package es.ccn.cursodejavaavanzado.proyectowebservice.service;

import java.util.logging.Logger;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2023-10-28T11:28:15.471+02:00
 * Generated source version: 4.0.3
 *
 */

@jakarta.jws.WebService(
                      serviceName = "ClienteServiceImplService",
                      portName = "ClienteServiceImplPort",
                      targetNamespace = "http://service.proyectowebservice.cursodejavaavanzado.ccn.es/",
                      wsdlLocation = "http://localhost:1234/WS/ClienteService?WSDL",
                      endpointInterface = "es.ccn.cursodejavaavanzado.proyectowebservice.service.ClienteService")

public class ClienteServiceImplPortImpl implements ClienteService {

    private static final Logger LOG = Logger.getLogger(ClienteServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see es.ccn.cursodejavaavanzado.proyectowebservice.service.ClienteService#actualizarCliente(es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente arg0)*
     */
    public void actualizarCliente(es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente arg0) {
        LOG.info("Executing operation actualizarCliente");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see es.ccn.cursodejavaavanzado.proyectowebservice.service.ClienteService#insertarCliente(es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente arg0)*
     */
    public void insertarCliente(es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente arg0) {
        LOG.info("Executing operation insertarCliente");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see es.ccn.cursodejavaavanzado.proyectowebservice.service.ClienteService#obtenerClienteById(int arg0)*
     */
    public es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente obtenerClienteById(int arg0) {
        LOG.info("Executing operation obtenerClienteById");
        System.out.println(arg0);
        try {
            es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente _return = new es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente();
            _return.setApellidos("Apellidos-1546225597");
            _return.setId(1154141324);
            _return.setNombre("Nombre-244002178");
            java.util.List<es.ccn.cursodejavaavanzado.proyectowebservice.service.Pedido> _returnPedidos = new java.util.ArrayList<es.ccn.cursodejavaavanzado.proyectowebservice.service.Pedido>();
            es.ccn.cursodejavaavanzado.proyectowebservice.service.Pedido _returnPedidosVal1 = new es.ccn.cursodejavaavanzado.proyectowebservice.service.Pedido();
            _returnPedidosVal1.setArticulo("Articulo-996701840");
            _returnPedidosVal1.setPrecio(new java.math.BigDecimal("3064662574086893671.6537280074394075200"));
            _returnPedidos.add(_returnPedidosVal1);
            _return.getPedidos().addAll(_returnPedidos);
            _return.setStrFechaNacimiento("StrFechaNacimiento-876935931");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see es.ccn.cursodejavaavanzado.proyectowebservice.service.ClienteService#obtenerClientes()*
     */
    public java.util.List<es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente> obtenerClientes() {
        LOG.info("Executing operation obtenerClientes");
        try {
            java.util.List<es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente> _return = new java.util.ArrayList<es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente>();
            es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente _returnVal1 = new es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente();
            _returnVal1.setApellidos("Apellidos-1388661306");
            _returnVal1.setId(-243934350);
            _returnVal1.setNombre("Nombre-1678568731");
            java.util.List<es.ccn.cursodejavaavanzado.proyectowebservice.service.Pedido> _returnVal1Pedidos = new java.util.ArrayList<es.ccn.cursodejavaavanzado.proyectowebservice.service.Pedido>();
            es.ccn.cursodejavaavanzado.proyectowebservice.service.Pedido _returnVal1PedidosVal1 = new es.ccn.cursodejavaavanzado.proyectowebservice.service.Pedido();
            _returnVal1PedidosVal1.setArticulo("Articulo-2015114526");
            _returnVal1PedidosVal1.setPrecio(new java.math.BigDecimal("5285918464422996883.2936003301096196543"));
            _returnVal1Pedidos.add(_returnVal1PedidosVal1);
            _returnVal1.getPedidos().addAll(_returnVal1Pedidos);
            _returnVal1.setStrFechaNacimiento("StrFechaNacimiento-461457693");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see es.ccn.cursodejavaavanzado.proyectowebservice.service.ClienteService#borrarCliente(int arg0)*
     */
    public void borrarCliente(int arg0) {
        LOG.info("Executing operation borrarCliente");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
