
package es.ccn.cursodejavaavanzado.proyectowebservice.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2023-10-28T11:28:15.391+02:00
 * Generated source version: 4.0.3
 *
 */
public final class ClienteService_ClienteServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.proyectowebservice.cursodejavaavanzado.ccn.es/", "ClienteServiceImplService");

    private ClienteService_ClienteServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ClienteServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ClienteServiceImplService ss = new ClienteServiceImplService(wsdlURL, SERVICE_NAME);
        ClienteService port = ss.getClienteServiceImplPort();

        {
        System.out.println("Invoking actualizarCliente...");
        es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente _actualizarCliente_arg0 = new es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente();
        _actualizarCliente_arg0.setApellidos("Apellidos-36764820");
        _actualizarCliente_arg0.setId(-1507560380);
        _actualizarCliente_arg0.setNombre("Nombre-1424978653");
        java.util.List<es.ccn.cursodejavaavanzado.proyectowebservice.service.Pedido> _actualizarCliente_arg0Pedidos = new java.util.ArrayList<es.ccn.cursodejavaavanzado.proyectowebservice.service.Pedido>();
        es.ccn.cursodejavaavanzado.proyectowebservice.service.Pedido _actualizarCliente_arg0PedidosVal1 = new es.ccn.cursodejavaavanzado.proyectowebservice.service.Pedido();
        _actualizarCliente_arg0PedidosVal1.setArticulo("Articulo-337411907");
        _actualizarCliente_arg0PedidosVal1.setPrecio(new java.math.BigDecimal("-2553366038274618972.3778796139300529362"));
        _actualizarCliente_arg0Pedidos.add(_actualizarCliente_arg0PedidosVal1);
        _actualizarCliente_arg0.getPedidos().addAll(_actualizarCliente_arg0Pedidos);
        _actualizarCliente_arg0.setStrFechaNacimiento("StrFechaNacimiento1398340100");
        port.actualizarCliente(_actualizarCliente_arg0);


        }
        {
        System.out.println("Invoking insertarCliente...");
        es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente _insertarCliente_arg0 = new es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente();
        _insertarCliente_arg0.setApellidos("Apellidos1738338143");
        _insertarCliente_arg0.setId(321777781);
        _insertarCliente_arg0.setNombre("Nombre-668991705");
        java.util.List<es.ccn.cursodejavaavanzado.proyectowebservice.service.Pedido> _insertarCliente_arg0Pedidos = new java.util.ArrayList<es.ccn.cursodejavaavanzado.proyectowebservice.service.Pedido>();
        es.ccn.cursodejavaavanzado.proyectowebservice.service.Pedido _insertarCliente_arg0PedidosVal1 = new es.ccn.cursodejavaavanzado.proyectowebservice.service.Pedido();
        _insertarCliente_arg0PedidosVal1.setArticulo("Articulo-948350490");
        _insertarCliente_arg0PedidosVal1.setPrecio(new java.math.BigDecimal("8674584692943296281.2222602947134766516"));
        _insertarCliente_arg0Pedidos.add(_insertarCliente_arg0PedidosVal1);
        _insertarCliente_arg0.getPedidos().addAll(_insertarCliente_arg0Pedidos);
        _insertarCliente_arg0.setStrFechaNacimiento("StrFechaNacimiento1389657523");
        port.insertarCliente(_insertarCliente_arg0);


        }
        {
        System.out.println("Invoking obtenerClienteById...");
        int _obtenerClienteById_arg0 = -1111978202;
        es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente _obtenerClienteById__return = port.obtenerClienteById(_obtenerClienteById_arg0);
        System.out.println("obtenerClienteById.result=" + _obtenerClienteById__return);


        }
        {
        System.out.println("Invoking obtenerClientes...");
        java.util.List<es.ccn.cursodejavaavanzado.proyectowebservice.service.Cliente> _obtenerClientes__return = port.obtenerClientes();
        System.out.println("obtenerClientes.result=" + _obtenerClientes__return);


        }
        {
        System.out.println("Invoking borrarCliente...");
        int _borrarCliente_arg0 = 1481276192;
        port.borrarCliente(_borrarCliente_arg0);


        }

        System.exit(0);
    }

}
